[theme]
primaryColor = "#00C0AF"
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1D1D1B"  
font = "sans serif"

[runner]
magicEnabled = false

[ui]
hideSidebarNav = false

